# Generated by Django 2.2.3 on 2019-08-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomment',
            name='headimg',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='author',
            field=models.TextField(default='匿名用户', null=True),
        ),
    ]
